name: Build and Test Feature Branch

on:
  pull_request:
      branches: [ develop ]
      types: [ opened, reopened ]

jobs:
    build-feature:
        # Define the platform to work in
        runs-on: ubuntu-latest
        
        steps:
            # Checkout your code into the container
            - uses: actions/checkout@v2
              with:
                # Making a pull_request on develop: Download the code from feature branch
                ref: ${{ github.event.pull_request.head.sha }}
            # Setup node and npm to your path
            - name: Use Node.js 
              uses: actions/setup-node@v2
              with:
                node-version: 16
            # Runs clean install of npm for automated environments
            - name: Clean Install
              run: npm ci
            # Run tests
            - name: Execute Tests
              run: npm test
            - name: Build project assest
              run: npm run build

# Automatic merge to develop branch
    # Execute only if the previos job ended succesfully
    merge-feature-into-develop:
      runs-on: ubuntu-latest
      needs: build-feature
      if: ${{ success() }}
  # Modify permissions for content and pull-request on GITHUB_TOKEN for push changes
      permissions:
        contents: write
        pull-requests: write
      
      steps:
    # Dowload the code from destination branch (develop) | fetch-depth: 0 to fech all history for all branches
        - uses: actions/checkout@v3
          with:
            ref: ${{ github.base_ref }}
            fetch-depth: 0

    # Merge to development branch if previos jobs ended succesfully
        - name: Merge to development branch
          if: ${{ success() }}
          run: |
            git config --global user.email "EMAIL-OF-WORKFLOW@USER"
            git config --global user.name "WORKFLOW-USER" 
            #Using -m "mesage" on merge command ins mandatori here in order to avoid open a text editor to write a commit message
            git merge --no-ff --verbose origin/${{ github.event.pull_request.head.ref }} -m "Merge pull request #${{ github.event.number }}"

    # Push changes after merge if previos jobs ended succesfully
        - name: Push changes after merge
          if: ${{ success() }}
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ github.base_ref }}
