name: Deploy app on EKS
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

permissions:
    id-token: write
    contents: write
    packages: write
          
jobs:

    Setup-Cache-Dependencies:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Use Node.js 
          uses: actions/setup-node@v2
          with:
            node-version: 18

        - name: Cache node modules
          uses: actions/cache@v2
          with:
            path: node_modules
            key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.OS }}-node-18-
        - run: npm ci

    Build-Application-Tests:
        runs-on: ubuntu-latest
        steps:
            # Checkout your code into the container
            - uses: actions/checkout@v2
              with:
                # Making a pull_request on develop: Download the code from feature branch
                ref: ${{ github.event.pull_request.head.sha }}
            # Setup node and npm to your path
            - name: Use Node.js 
              uses: actions/setup-node@v2
              with:
                node-version: 18
            # Runs clean install of npm for automated environments
            - run: npm ci
            # Run tests
            - name: Ejecutar pruebas
              run: npm test
        
    Deploy-to-QA:
        name: Deploy to Quality Assurance
        needs: [Setup-Cache-Dependencies, Build-Application-Tests]
        if: github.event_name == 'pull_request'
        # Define the platform to work in
        runs-on: ubuntu-latest
        environment:
            name: Development

        steps:
        - name: Install kubectl
          uses: azure/setup-kubectl@v3
          with:
            version: 'v1.28.0'
          id: install

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v3
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
            role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
            role-session-name: ${{ secrets.AWS_ROLE_SESSION_NAME }}
    
        - name: Update kube config
          run: aws eks update-kubeconfig --name eks-demo --region us-east-2
      
        - name: Deploy to EKS
          run: |
              kubectl apply -f eks/deployment-qa.yaml
              kubectl apply -f eks/service-qa.yaml

    QA-EKS-Values:
        name: Get QA Kubernetes Values
        needs: [Setup-Cache-Dependencies, Deploy-to-QA]
        if: success()
        # Define the platform to work in
        runs-on: ubuntu-latest
        environment:
          name: Development

        steps:
        - name: Install kubectl
          uses: azure/setup-kubectl@v3
          with:
            version: 'v1.28.0'
          id: install
      
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v3
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
            role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
            role-session-name: ${{ secrets.AWS_ROLE_SESSION_NAME }}

        - name: Update kube config
          run: aws eks update-kubeconfig --name eks-demo --region us-east-2

        - name: Get Quality Assurance EKS Values
          run: |
              kubectl get ns
              kubectl get deployment -n quality-assurance -o wide
              kubectl get service -n quality-assurance
              kubectl get pods -o wide -n quality-assurance
    

    Deploy-to-Stg:
        name: Deploy to Staging
        needs: [Setup-Cache-Dependencies, Build-Application-Tests]
        if: github.event.ref == 'refs/heads/main'
        # Define the platform to work in
        runs-on: ubuntu-latest
        environment:
            name: Staging
        
        steps:
        - name: Install kubectl
          uses: azure/setup-kubectl@v3
          with:
            version: 'v1.28.0'
          id: install
            
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v3
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
            role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
            role-session-name: ${{ secrets.AWS_ROLE_SESSION_NAME }}
            
        - name: Update kube config
          run: aws eks update-kubeconfig --name eks-demo --region us-east-2
              
        - name: Deploy to EKS
          run: |
            kubectl apply -f eks/deployment-stg.yaml
            kubectl apply -f eks/service-stg.yaml

    Stg-EKS-Values:
        name: Get Stg Kubernetes Values
        needs: [Setup-Cache-Dependencies, Deploy-to-Stg]
        if: success()
        # Define the platform to work in
        runs-on: ubuntu-latest
        environment:
          name: Staging

        steps:
        - name: Install kubectl
          uses: azure/setup-kubectl@v3
          with:
            version: 'v1.28.0'
          id: install
      
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v3
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
            role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
            role-session-name: ${{ secrets.AWS_ROLE_SESSION_NAME }}

        - name: Update kube config
          run: aws eks update-kubeconfig --name eks-demo --region us-east-2

        - name: Get Staging EKS Values
          run: |
              kubectl get ns
              kubectl get deployment -n staging -o wide
              kubectl get service -n staging
              kubectl get pods -o wide -n staging

    Deploy-to-Prod:
        name: Deploy to Production
        needs: [Setup-Cache-Dependencies, Deploy-to-Stg]
        # Define the platform to work in
        runs-on: ubuntu-latest
        environment:
                name: Production
                
        steps:
        - name: Install kubectl
          uses: azure/setup-kubectl@v3
          with:
            version: 'v1.28.0'
          id: install
                    
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v3
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
            role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
            role-session-name: ${{ secrets.AWS_ROLE_SESSION_NAME }}
                    
        - name: Update kube config
          run: aws eks update-kubeconfig --name eks-demo --region us-east-2
                      
        - name: Deploy to EKS
          run: |
            kubectl apply -f eks/deployment-prd.yaml
            kubectl apply -f eks/service-prd.yaml

    Image-to-ECR:
        name: Docker Image to ECR
        needs: [Setup-Cache-Dependencies, Deploy-to-Prod]
        if: success()
        runs-on: ubuntu-latest
        environment:
          name: Production
        steps:
        - name: Install kubectl
          uses: azure/setup-kubectl@v3
          with:
            version: 'v1.28.0'
          id: install

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v3
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
            role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
            role-session-name: ${{ secrets.AWS_ROLE_SESSION_NAME }}

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1
          with:
            mask-password: 'true'
                    
        - name: Tag, and push docker image to Amazon ECR
          env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            ECR_REPOSITORY: express
            IMAGE_TAG: ${{ github.sha }}
          run: |
                docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
                docker push $ECR_REGISTRY/$ECR_REPOSITORY

    Prod-EKS-Values:
        name: Get Prod Kubernetes Values
        needs: [Setup-Cache-Dependencies, Deploy-to-Prod]
        if: success()
        # Define the platform to work in
        runs-on: ubuntu-latest
        environment:
          name: Production

        steps:
        - name: Install kubectl
          uses: azure/setup-kubectl@v3
          with:
            version: 'v1.28.0'
          id: install
      
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v3
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
            role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
            role-session-name: ${{ secrets.AWS_ROLE_SESSION_NAME }}

        - name: Update kube config
          run: aws eks update-kubeconfig --name eks-demo --region us-east-2

        - name: Get Production EKS Values
          run: |
              kubectl get ns
              kubectl get deployment -n production -o wide
              kubectl get service -n production
              kubectl get pods -o wide -n production

# Call workflow: "create release"
        - name: trigger create release
          if: success()
          uses: peter-evans/repository-dispatch@v2
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            repository: ${{ github.repository }}
            event-type: create-release
            client-payload: '{ "base_branch": "${{ github.base_ref }}" }'
