name: Create Release
on:
  push:
    branches:
      - main
      
  repository_dispatch:
    types: [create-release]

permissions:
    id-token: write
    contents: write
    packages: write

jobs:
    Release:
      name: Upload Release Asset
      runs-on: ubuntu-latest
      environment:
        name: Production
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '14'
  
        - name: Install dependencies
          run: npm install

      # Use semantic-release to determine and create a new version
        - name: Semantic Release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: npx semantic-release

        - name: Build project # Build your project, using zip for an example artifact
          run: |
            zip --junk-paths hello-world README.md

        - name: Get the latest release tag
          id: get_version
          run: echo "::set-output name=version::$(git describe --tags --abbrev=0)"

        - name: Create Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ steps.get_version.outputs.version }}
            release_name: Release ${{ steps.get_version.outputs.version }}
            draft: false
            prerelease: false

        - name: Upload Release Asset
          id: upload-release-asset 
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./hello-world.zip
            asset_name: hello-world.zip
            asset_content_type: application/zip
            