name: Create Release
on:
  repository_dispatch:
    types: [create-release]

permissions:
    id-token: write
    contents: write
    packages: write

jobs:
    Release:
      name: Upload Release Asset
      runs-on: ubuntu-latest
      environment:
        name: Production
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: 18
  
        - name: Install dependencies
          run: npm ci

        - name: Build project 
          run: |
            zip --junk-paths hello-world README.md

        - name: Semantic Release
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: npx semantic-release

      # Wait for a few seconds to ensure the release is registered on GitHub
        - name: Wait for GitHub to register the release
          run: sleep 10

        - name: Get the latest release tag
          id: get_version
          run: echo "::set-output name=version::$(git describe --tags --abbrev=0)"

        - name: Upload Release Asset
          id: upload-release-asset 
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ steps.get_version.outputs.version }}
            asset_path: ./hello-world.zip
            asset_name: hello-world.zip
            asset_content_type: application/zip
            