name: Create Release
on:
  repository_dispatch:
    types: [create-release]

permissions:
    id-token: write
    contents: write
    packages: write

jobs:
    Release:
      name: Upload Release Asset
      runs-on: ubuntu-latest
      environment:
        name: Production
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: 18
  
        - name: Install dependencies
          run: npm ci

        - name: Semantic Release
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: npx semantic-release

            